name: CodAcy coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Generate coverage report
      run: mvn jacoco:report

    - name: Download Codacy Coverage Reporter
      run: wget -O tools/codacy-coverage-reporter-assembly.jar https://github.com/codacy/codacy-coverage-reporter/releases/latest/download/codacy-coverage-reporter-assembly.jar

    - name: Upload coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: java -jar tools/codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
